# -------------------------- Trainer args --------------------------
# metrics to monitor
monitor: pearson
metric_mode: max

# early stopping
early_stopping: True
patience: 3
min_delta: 0.0
save_top_k: 3
min_epochs: 1
max_epochs: 3

gradient_clip_val: 1.0
gpus: 1
#distributed_backend: ddp
batch_size: 4
accumulate_grad_batches: 4
loader_workers: 4

#limit_train_batches: 5
#limit_val_batches: 3

# ---------------------- Optimizer args --------------------------
optimizer: Adam
learning_rate: 0.00002
encoder_learning_rate: 0.00001

# ---------------------- Scheduler args --------------------------
scheduler: constant

# -------------------------- Data --------------------------
data_type: csv
train_path: data/apequest/train.csv
val_path: data/apequest/test.csv

# ----------------------- Model args --------------------------
model: CometEstimator
nr_frozen_epochs: 1
loss: mse
encoder_model: XLMR
pretrained_model: xlmr.base

pool: avg
layer: mix

# Feed Forward definition:
dropout: 0.1
activations: Tanh
hidden_sizes: "1536,768"
#scalar_mix_dropout: 0.1