# -------------------------- Trainer args --------------------------
# metrics to monitor
monitor: kendall
metric_mode: max
period: 1

# early stopping
early_stopping: True
patience: 3
min_delta: 0.0
save_top_k: 1
min_epochs: 1
max_epochs: 3

gradient_clip_val: 1.0
gpus: 1
distributed_backend: dp
batch_size: 4
accumulate_grad_batches: 4
loader_workers: 4

# ---------------------- Optimizer args --------------------------
optimizer: Adam
learning_rate: 0.00001

# ---------------------- Scheduler args --------------------------
scheduler: constant

# -------------------------- Data --------------------------
data_type: csv
train_path: data/wmt/train1718.csv
val_path: data/wmt/val1718.csv

# percentage of training to be used after one epoch to control overfit (default is 1%)
train_val_percent_check: 0.01

# ----------------------- Model args --------------------------
model: CometRanker
nr_frozen_epochs: 0
encoder_model: XLMR
pretrained_model: xlmr.base

pool: avg
layer: mix
scalar_mix_dropout: 0.1