seed: 12
monitor: pearson
metric_mode: max
early_stopping: True
patience: 3
min_delta: 0.0
save_top_k: 2
save_weights_only: True 
min_epochs: 1
max_epochs: 3
gradient_clip_val: 1.0
gpus: 1
#precision: 16
#amp_level: O2
batch_size: 4
accumulate_grad_batches: 4
loader_workers: 4

optimizer: Adam
learning_rate: 0.00002
encoder_learning_rate: 0.00001
scheduler: constant

train_path: data/qt21/train.csv
val_path: data/qt21/test.csv

model: CometEstimator
nr_frozen_epochs: 1
loss: mse
encoder_model: XLMR
pretrained_model: xlmr.base

layer: mix
scalar_mix_dropout: 0.1
pool: avg

dropout: 0.1
activations: Tanh
hidden_sizes: "1536,768"
