seed: 12
monitor: kendall
metric_mode: max
early_stopping: True
patience: 3
min_delta: 0.0
save_top_k: 1
save_weights_only: True 
min_epochs: 1
max_epochs: 3
gradient_clip_val: 1.0
gpus: 1
#precision: 16
#amp_level: O2
batch_size: 4
accumulate_grad_batches: 4
loader_workers: 4

# ---------------------- Optimizer args --------------------------
optimizer: Adam
learning_rate: 0.00001

# ---------------------- Scheduler args --------------------------
scheduler: constant

# -------------------------- Data --------------------------
data_type: csv
train_path: data/wmt/train1718.csv
val_path: data/wmt/test1718.csv
limit_val_batches: 2000

# ----------------------- Model args --------------------------
model: CometRanker
nr_frozen_epochs: 0
encoder_model: XLMR
pretrained_model: xlmr.base

pool: avg
layer: mix
scalar_mix_dropout: 0.1